//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartamentoServiciosEscolaresCBTis123.Logica.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class areascampos
    {
        public areascampos()
        {
            this.materias = new HashSet<materias>();
        }
    
        public int idAreacampo { get; set; }
        public string nombre { get; set; }
        public string acuerdo { get; set; }
    
        public virtual ICollection<materias> materias { get; set; }
    }
}
