//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartamentoServiciosEscolaresCBTis123.Logica.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificaciones
    {
        // Propiedades mías
        public string nControl
        {
            get
            {
                return estudiantes.ncontrol;
            }
        }


        // Propiedades del modelo
        public int idCalificaciones { get; set; }
        public double calificacionParcial1 { get; set; }
        public double calificacionParcial2 { get; set; }
        public double calificacionParcial3 { get; set; }
        public int asistenciasParcial1 { get; set; }
        public int asistenciasParcial2 { get; set; }
        public int asistenciasParcial3 { get; set; }
        public string tipoDeAcreditacion { get; set; }
        public bool recursamiento { get; set; }
        public bool firmado { get; set; }
        public int idEstudiante { get; set; }
        public int idCatedra { get; set; }
    
        public virtual estudiantes estudiantes { get; set; }
        public virtual catedras catedras { get; set; }

        // Propiedades mías
        public double promedio
        {
            get
            {
                return (calificacionParcial1 + calificacionParcial2 + calificacionParcial3) / 3;
            }
        }
        public int asistenciasTotales
        {
            get
            {
                return asistenciasParcial1 + asistenciasParcial2 + asistenciasParcial3;
            }
        }
    }
}
