//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartamentoServiciosEscolaresCBTis123.Logica.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class calificacionessemestrales
    {
        // Propiedades mías
        public string nControl
        {
            get
            {
                return estudiantes.ncontrol;
            }
        }


        // Propiedades del modelo
        public int idCalificacionesSemestrales { get; set; }
        public Nullable<double> calificacionParcial1 { get; set; }
        public Nullable<double> calificacionParcial2 { get; set; }
        public Nullable<double> calificacionParcial3 { get; set; }
        public Nullable<int> asistenciasParcial1 { get; set; }
        public Nullable<int> asistenciasParcial2 { get; set; }
        public Nullable<int> asistenciasParcial3 { get; set; }
        public string tipoDeAcreditacion { get; set; }
        public bool recursamiento { get; set; }
        public bool firmado { get; set; }
        public int idEstudiante { get; set; }
        public int idCatedra { get; set; }
    
        public virtual estudiantes estudiantes { get; set; }
        public virtual catedras catedras { get; set; }

        // Propiedades mías
        public double? promedio
        {
            get
            {
                int nulos = 0;

                if (!calificacionParcial1.HasValue)
                    nulos++;

                if (!calificacionParcial2.HasValue)
                    nulos++;

                if (!calificacionParcial3.HasValue)
                    nulos++;

                double total = (calificacionParcial1.HasValue ? calificacionParcial1.Value : 0.0) + (calificacionParcial2.HasValue ? calificacionParcial2.Value : 0.0) + (calificacionParcial3.HasValue ? calificacionParcial3.Value : 0.0);

                if (nulos < 3)
                {
                    return total / (3 - nulos);
                }
                else
                {
                    return null;
                }
            }
        }
        public int? asistenciasTotales
        {
            get
            {
                int nulos = 0;

                if (!asistenciasParcial1.HasValue)
                    nulos++;

                if (!asistenciasParcial2.HasValue)
                    nulos++;

                if (!asistenciasParcial3.HasValue)
                    nulos++;

                if (nulos < 3)
                {
                    return (asistenciasParcial1.HasValue ? asistenciasParcial1.Value : 0) + (asistenciasParcial2.HasValue ? asistenciasParcial2.Value : 0) + (asistenciasParcial3.HasValue ? asistenciasParcial3.Value : 0);
                }
                else
                {
                    return null;
                }
            }
        }
    }
}
