//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartamentoServiciosEscolaresCBTis123.Logica.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class carreras
    {
        public carreras()
        {
            this.materias = new HashSet<materias>();
            this.modulos = new HashSet<modulos>();
        }
    
        public int idCarrera { get; set; }
        public string nombre { get; set; }
        public string abreviatura { get; set; }
        public string acuerdo { get; set; }
        public string bachilleratociencias { get; set; }
    
        public virtual ICollection<materias> materias { get; set; }
        public virtual ICollection<modulos> modulos { get; set; }


        // Métodos míos
        public override string ToString()
        {
            return nombre + " (" + abreviatura + ")";
        }
    }
}
