//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartamentoServiciosEscolaresCBTis123.Logica.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CBTis123_Entities : DbContext
    {
        public CBTis123_Entities()
            : base("name=CBTis123_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<academias> academias { get; set; }
        public virtual DbSet<areascampos> areascampos { get; set; }
        public virtual DbSet<calificaciones_semestrales> calificaciones_semestrales { get; set; }
        public virtual DbSet<carreras> carreras { get; set; }
        public virtual DbSet<catedras> catedras { get; set; }
        public virtual DbSet<datos_varios> datos_varios { get; set; }
        public virtual DbSet<docentes> docentes { get; set; }
        public virtual DbSet<estudiantes> estudiantes { get; set; }
        public virtual DbSet<fichas> fichas { get; set; }
        public virtual DbSet<grupos> grupos { get; set; }
        public virtual DbSet<grupos_estudiantes> grupos_estudiantes { get; set; }
        public virtual DbSet<historial_calificaciones_semestrales> historial_calificaciones_semestrales { get; set; }
        public virtual DbSet<localidades> localidades { get; set; }
        public virtual DbSet<materias> materias { get; set; }
        public virtual DbSet<modulos> modulos { get; set; }
        public virtual DbSet<municipios> municipios { get; set; }
        public virtual DbSet<planea_d16_2017> planea_d16_2017 { get; set; }
        public virtual DbSet<planea_mate16_d1_2017> planea_mate16_d1_2017 { get; set; }
        public virtual DbSet<prefichas> prefichas { get; set; }
        public virtual DbSet<prefichas2016> prefichas2016 { get; set; }
        public virtual DbSet<prefichas2017> prefichas2017 { get; set; }
        public virtual DbSet<prefichas2018> prefichas2018 { get; set; }
        public virtual DbSet<semestres> semestres { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
