//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartamentoServiciosEscolaresCBTis123.Logica.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class historialcalificacionessemestrales
    {
        public int idHistorialCalificacionesSemestrales { get; set; }
        public string nombreCampo { get; set; }
        public string valorAnterior { get; set; }
        public string valorNuevo { get; set; }
        public int idCalificacionesSemestrales { get; set; }
    
        public virtual calificacionessemestrales calificacionessemestrales { get; set; }
    }
}
