//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartamentoServiciosEscolaresCBTis123.Logica.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_calificaciones_semestrales
    {
        public int idHistorial_Calificacion_Semestral { get; set; }
        public string cambios { get; set; }
        public int idCalificacion_Semestral { get; set; }
    
        public virtual calificaciones_semestrales calificaciones_semestrales { get; set; }
    }
}
