//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartamentoServiciosEscolaresCBTis123.Logica.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class materias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public materias()
        {
            this.catedras = new HashSet<catedras>();
        }
    
        public int idMateria { get; set; }
        public Nullable<int> idAreacampo { get; set; }
        public int idAcademia { get; set; }
        public Nullable<int> idCarrera { get; set; }
        public Nullable<int> idModulo { get; set; }
        public short subModulo { get; set; }
        public short semestre { get; set; }
        public string nombre { get; set; }
        public string abreviatura { get; set; }
        public string componenteF { get; set; }
        public string propedeutica { get; set; }
        public short hrsSemana { get; set; }
        public short hrsSemestre { get; set; }
    
        public virtual areascampos areascampos { get; set; }
        public virtual carreras carreras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catedras> catedras { get; set; }
        public virtual modulos modulos { get; set; }
    }
}
