//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartamentoServiciosEscolaresCBTis123.Logica.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class planea_mate16_d1_2017
    {
        public int id { get; set; }
        public string ncontrol { get; set; }
        public string nombre { get; set; }
        public string grupo { get; set; }
        public string respuestas { get; set; }
        public bool aplicado { get; set; }
        public int aciertos { get; set; }
        public int porcentaje { get; set; }
    }
}
