//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartamentoServiciosEscolaresCBTis123.Logica.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class planea_d16_2017
    {
        public int idPlanea_d16_2017 { get; set; }
        public string ncontrol { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string nombres { get; set; }
        public string grupo { get; set; }
        public string periodo { get; set; }
        public string respuestas { get; set; }
    }
}
