//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartamentoServiciosEscolaresCBTis123.Logica.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class prefichas2017
    {
        public int idPreficha { get; set; }
        public string nombres { get; set; }
        public string apellidop { get; set; }
        public string apellidom { get; set; }
        public System.DateTime fechanac { get; set; }
        public string curp { get; set; }
        public string estadoc { get; set; }
        public string genero { get; set; }
        public string estadonac { get; set; }
        public string municipionac { get; set; }
        public string estadovive { get; set; }
        public string municipiovive { get; set; }
        public string localidad { get; set; }
        public string colonia { get; set; }
        public string calle { get; set; }
        public string numero { get; set; }
        public string codigop { get; set; }
        public string ladalocal { get; set; }
        public string numlocal { get; set; }
        public string celulare { get; set; }
        public string celularr { get; set; }
        public string correoe { get; set; }
        public string secundaria { get; set; }
        public string clavesecundaria { get; set; }
        public string modalidad { get; set; }
        public string primera { get; set; }
        public string segunda { get; set; }
        public string tercera { get; set; }
        public int aula { get; set; }
        public string especialidad { get; set; }
    }
}
