//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DepartamentoServiciosEscolaresCBTis123.Logica.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class semestres
    {
        public semestres()
        {
            this.grupos = new HashSet<grupos>();
        }
    
        public int idSemestre { get; set; }
        public string nombre { get; set; }
        public string nombrecorto { get; set; }
        public string nombrecorto2 { get; set; }
        public string nombrecorto3 { get; set; }
    
        public virtual ICollection<grupos> grupos { get; set; }

        // Métodos míos
        public override string ToString()
        {
            return nombre + " (" + nombrecorto2 + ")";
        }
    }
}
